# Generated by Django 3.2.6 on 2021-08-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymapp', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='photo',
            field=models.ImageField(null=True, upload_to='transactions'),
        ),
    ]
